apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: {{ name }}
  namespace: bidrag
  labels:
    team: bidrag
spec:
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
        destinations:
          - id: loki
          - id: elastic
          - id: secure_logs
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  accessPolicy:
    inbound:
      rules:
      {{#each azureAccessInbound}}
          - application: {{this.application}}
            namespace: {{this.namespace}}
            cluster: {{this.cluster}}
      {{/each}}
    outbound:
      external:
        - host: {{ azure.bidrag_organisasjon_url }}
  image: {{ image }}
  kafka:
    pool: {{ kafka.pool }}
  liveness:
    path: /actuator/health
    initialDelay: 120
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /actuator/health
    initialDelay: 70
    timeout: 1
  prometheus:
    enabled: true
    path: /actuator/prometheus
  secureLogs:
    enabled: true
  resources:
    limits:
      cpu: {{ spec.resources.limits.cpu }}
      memory: {{ spec.resources.limits.memory }}
    requests:
      cpu: {{ spec.resources.requests.cpu }}
      memory: {{ spec.resources.requests.memory }}
  replicas:
    cpuThresholdPercentage: 80
    min: {{ spec.replicas.min }}
    max: {{ spec.replicas.max }}
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  gcp:
    sqlInstances:
      - name: {{ dbname }}
        type: POSTGRES_15
        diskSize: {{ spec.gcp.sqlInstances.diskSize }}
        databases:
          - name: {{ dbname }}
            envVarPrefix: DB
        tier: {{ spec.gcp.sqlInstances.tier }}
        pointInTimeRecovery: {{ spec.gcp.sqlInstances.pointInTimeRecovery }}
        diskAutoresize: {{ spec.gcp.sqlInstances.diskAutoresize }}
        flags:
          - name: "cloudsql.enable_pgaudit"
            value: "{{ spec.gcp.sqlInstances.auditlog }}"
          - name: "pgaudit.log"
            value: "write"
          - name: "pgaudit.log_parameter"
            value: "on"
  env:
    - name: TOPIC_VEDTAK
      value: {{ kafka-topic-vedtak }}
    - name: TOPIC_VEDTAKSFORSLAG
      value: {{ kafka-topic-vedtaksforslag }}
    - name: BIDRAG_ORGANISASJON_URL
      value: https://{{ azure.bidrag_organisasjon_url }}/bidrag-organisasjon
    - name: BIDRAG_ORGANISASJON_SCOPE
      value: {{ azure.bidrag_organisasjon_scope }}
    - name: SPRING_PROFILES_ACTIVE
      value: {{ spring-profiles }}