apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
  labels:
    team: bidrag
spec:
  image: {{ image }}
  azure:
    application:
      enabled: true
  liveness:
    path: /internal/actuator/health
    initialDelay: 70
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/actuator/health
    initialDelay: 70
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  ingresses:
    - {{ ingress }}
  gcp:
    sqlInstances:
      - name: bidrag-vedtak
        type: POSTGRES_12
        databases:
          - name: bidrag-vedtak-db
            envVarPrefix: DB
