apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: {{ name }}
  namespace: bidrag
  labels:
    team: bidrag
spec:
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  accessPolicy:
    inbound:
      rules:
      {{#each azureAccessInbound}}
          - application: {{this.application}}
            namespace: {{this.namespace}}
            cluster: {{this.cluster}}
      {{/each}}
  image: {{ image }}
  kafka:
    pool: {{ kafka.pool }}
  liveness:
    path: /actuator/health
    initialDelay: 120
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /actuator/health
    initialDelay: 70
    timeout: 1
  prometheus:
    enabled: true
    path: /actuator/prometheus
  secureLogs:
    enabled: true
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  replicas:
    cpuThresholdPercentage: 80
    min: {{ spec.replicas.min }}
    max: {{ spec.replicas.max }}
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  gcp:
    sqlInstances:
      - name: {{ dbname }}
        type: POSTGRES_15
        databases:
          - name: {{ dbname }}
            envVarPrefix: DB
        tier: {{ spec.gcp.sqlInstances.tier }}
        diskAutoresize: {{ spec.gcp.sqlInstances.diskAutoresize }}
  env:
    - name: TOPIC_VEDTAK
      value: {{ kafka-topic-vedtak }}