name: bidrag-vedtak
ingress: https://bidrag-vedtak.intern.nav.no
dbname: bidrag-vedtak-prod
kafka:
  pool: nav-prod
kafka-topic-vedtak: bidrag.vedtak
inbound:
  bidrag-revurder-forskudd-app: bidrag-revurder-forskudd-data
