name: bidrag-vedtak
ingresses:
  - https://bidrag-vedtak.intern.nav.no
dbname: bidrag-vedtak-prod
kafka:
  pool: nav-prod
kafka-topic-vedtak: bidrag.vedtak
inbound:
  bidrag-revurder-forskudd-app: bidrag-revurder-forskudd-data
azureAccessInbound:
  - application: bidrag-vedtak
    namespace: bidrag
    cluster: prod-gcp
  - application: bidrag-revurder-forskudd-data
    namespace: bidrag
    cluster: prod-gcp
  - application: bisys
    namespace: bidrag
    cluster: prod-fss
  - application: bidrag-dokument-bestilling
    namespace: bidrag
    cluster: prod-gcp
  - application: bidrag-dokument-forsendelse
    namespace: bidrag
    cluster: prod-gcp
  - application: bidrag-ui
    namespace: bidrag
    cluster: prod-fss
spec:
  replicas:
    min: 2
    max: 4
  gcp:
    sqlInstances:
      tier: db-custom-1-3840
      diskAutoresize: true
#azure:
#  tenant: nav.no
#  bidrag_organisasjon_url: https://bidrag-organisasjon.prod-fss-pub.nais.io/bidrag-organisasjon
#  bidrag_organisasjon_scope: prod-fss.bidrag.bidrag-organisasjon