apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: {{ name }}
  namespace: bidrag
  labels:
    team: bidrag
spec:
  azure:
    application:
      enabled: true
  image: {{ image }}
  liveness:
    path: /bidrag-vedtak/actuator/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /bidrag-vedtak/actuator/health
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /bidrag-vedtak/actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  ingresses:
    - {{ ingress }}
  gcp:
    sqlInstances:
      - name: bidrag-vedtak-feature
        tier: db-custom-1-3840
        type: POSTGRES_12
        cascadingDelete: true
        databases:
          - name: bidrag-vedtak-feature
            envVarPrefix: DB
