apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: {{ name }}
  namespace: bidrag
  labels:
    team: bidrag
spec:
  azure:
    application:
      enabled: true
  image: {{ image }}
  liveness:
    path: /bidrag-vedtak/actuator/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /bidrag-vedtak/actuator/health
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /bidrag-vedtak/actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
    ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
#  filesFrom:
#    - secret: secret-for-bidrag-vedtak-dev-gcp
#      mountPath: /var/run/secrets/secret-for-bidrag-vedtak-dev-gcp
#      # secret will be available in the file /var/run/secrets/my-secret/secret
#  envFrom:
#    - secret: secret-for-bidrag-vedtak-dev-gcp
#      # secret will be made available as environment variables
  gcp:
    sqlInstances:
      - name: bidrag-vedtak-feature
        tier: db-custom-1-3840
        type: POSTGRES_12
        databases:
          - name: bidrag-vedtak-feature
            envVarPrefix: DB
  accesspolicy:
    inbound:
      rules:
        - application: {{ allow_inbound_apps }}