apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
  labels:
    team: bidrag
spec:
  image: {{ image }}
  azure:
    application:
      enabled: true
  liveness:
    path: /bidrag-vedtak/actuator/health
    initialDelay: 70
    timeout: 1
    periodSeconds: 5
    failureThreshold: 15
  readiness:
    path: /bidrag-vedtak/actuator/health
    initialDelay: 70
    timeout: 1
  prometheus:
    enabled: true
    path: /bidrag-vedtak/actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  ingresses:
    - {{ ingress }}
  gcp:
    sqlInstances:
      - name: bidrag-vedtak-dev
        tier: db-custom-1-3840
        type: POSTGRES_12
        databases:
          - name: bidrag-vedtak-dev
            envVarPrefix: DB
  accesspolicy:
    inbound:
      rules:
        - application: {{ allow_inbound_apps }}
    outbound:
      external:
        - host: api-gw-q1.oera.no
        - host: login.microsoftonline.com