-- Table: engangsbeløp

-- DROP TABLE engangsbeløp;

CREATE TABLE IF NOT EXISTS engangsbeløp
(
    engangsbeløp_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    vedtak_id integer NOT NULL,
    lopenr integer,
    endrer_engangsbeløp_id integer,
    type varchar(50) NOT NULL,
    sak_id varchar(20) NOT NULL,
    skyldner_id varchar(20) NOT NULL,
    kravhaver_id varchar(20) NOT NULL,
    mottaker_id varchar(20) NOT NULL,
    beløp float,
    valutakode varchar(10),
    resultatkode varchar(255) NOT NULL,
    referanse varchar(32),
    innkreving varchar(20) NOT NULL,
    CONSTRAINT engangsbeløp_pkey PRIMARY KEY (engangsbeløp_id),
    CONSTRAINT engangsbeløp_fk_vedtak_id FOREIGN KEY (vedtak_id)
        REFERENCES vedtak (vedtak_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    UNIQUE (vedtak_id, lopenr)
)

    TABLESPACE pg_default;

CREATE INDEX idx_engangsbeløp_1 ON engangsbeløp(vedtak_id);