-- Table: vedtak

-- DROP TABLE vedtak;

CREATE TABLE IF NOT EXISTS vedtak
(
    vedtaksid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    kilde varchar(20) NOT NULL default 'Manuelt',
    type varchar(50) NOT NULL,
    opprettet_av varchar(255) NOT NULL,
    opprettet_av_navn varchar(255),
    kildeapplikasjon varchar(255) NOT NULL,
    vedtakstidspunkt timestamp NOT NULL,
    enhetsnummer character(4),
    innkreving_utsatt_til_dato date,
    fastsatt_i_land varchar(255),
    opprettet_tidspunkt timestamp DEFAULT now() NOT NULL,
    CONSTRAINT vedtak_pkey PRIMARY KEY (vedtaksid)
)

    TABLESPACE pg_default;