-- Table: behandlingsreferanse

-- DROP TABLE behandlingsreferanse;

CREATE TABLE IF NOT EXISTS behandlingsreferanse
(
    behandlingsreferanseid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    vedtaksid integer NOT NULL,
    kilde text NOT NULL,
    referanse text NOT NULL,
    CONSTRAINT behandlingsreferanse_pkey PRIMARY KEY (behandlingsreferanseid),
    CONSTRAINT fk_behandlingsreferanse_id FOREIGN KEY (vedtaksid)
        REFERENCES vedtak (vedtaksid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    UNIQUE (vedtaksid, kilde, referanse)
)

    TABLESPACE pg_default;

CREATE INDEX idx_behandlingsreferanse_1 ON behandlingsreferanse(vedtaksid);