-- Table: vedtak

-- DROP TABLE vedtak;

CREATE TABLE IF NOT EXISTS vedtak
(
    vedtak_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    opprettet_av character(7),
    opprettet_timestamp timestamp,
    enhetsnummer character(4),
    CONSTRAINT vedtak_pkey PRIMARY KEY (vedtak_id)
)

    TABLESPACE pg_default;