-- Table: stønadsendring

-- DROP TABLE stønadsendring;

CREATE TABLE IF NOT EXISTS stønadsendring
(
    stønadsendring_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    type varchar(20) NOT NULL,
    vedtak_id integer NOT NULL,
    sak_id varchar(20) NOT NULL,
    skyldner_id varchar(20) NOT NULL,
    kravhaver_id varchar(20) NOT NULL,
    mottaker_id varchar(20) NOT NULL,
    indeksregulering_aar character(4),
    innkreving varchar(20) NOT NULL,
    CONSTRAINT stonad_pkey PRIMARY KEY (stønadsendring_id),
    CONSTRAINT fk_vedtak_id FOREIGN KEY (vedtak_id)
        REFERENCES vedtak (vedtak_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    UNIQUE (vedtak_id, type, skyldner_id, kravhaver_id, sak_id)
)
    TABLESPACE pg_default;

CREATE INDEX idx_stønadsendring_1 ON stønadsendring(vedtak_id) ;