-- Table: periode

-- DROP TABLE periode;

CREATE TABLE IF NOT EXISTS periode
(
    periodeid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    stønadsendringsid integer NOT NULL,
    fom date NOT NULL,
    til date,
    beløp float,
    valutakode varchar(10),
    resultatkode varchar(255) NOT NULL,
    delytelse_id varchar(32),
    CONSTRAINT periode_pkey PRIMARY KEY (periodeid),
    CONSTRAINT fk_stønad_id FOREIGN KEY (stønadsendringsid)
        REFERENCES stønadsendring (stønadsendringsid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    UNIQUE (stønadsendringsid, fom)
)
    TABLESPACE pg_default;

CREATE INDEX idx_periode_1 ON periode(stønadsendringsid);