-- Table: periode

-- DROP TABLE grunnlag;

CREATE TABLE IF NOT EXISTS grunnlag
(
    grunnlag_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    grunnlag_referanse varchar(50),
    vedtak_id,
    grunnlag_type varchar(20),
    grunnlag_innhold jsonb,
    CONSTRAINT grunnlag_pkey PRIMARY KEY (grunnlag_id),
    CONSTRAINT fk_vedtak_id FOREIGN KEY (vedtak_id)
        REFERENCES vedtak (vedtak_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    UNIQUE (vedtak_id, grunnlag_referanse)
)

    TABLESPACE pg_default;