-- Table: vedtak

-- DROP TABLE vedtak;

CREATE TABLE IF NOT EXISTS vedtak
(
    vedtak_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    vedtak_type varchar(50) NOT NULL default 'Manuelt',
    enhet_id character(4) NOT NULL,
    vedtak_dato date NOT NULL,
    opprettet_av varchar(50) NOT NULL,
    opprettet_timestamp timestamp DEFAULT now() NOT NULL,
    ekstern_referanse varchar(20),
    utsatt_til_dato date,
    CONSTRAINT vedtak_pkey PRIMARY KEY (vedtak_id)
)

    TABLESPACE pg_default;