-- Table: stonad

-- DROP TABLE stonad;

CREATE TABLE IF NOT EXISTS stonad
(
    stonad_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    stonad_type text,
    vedtak_id integer,
    behandling_id text,
    skyldner_id character(20),
    kravhaver_id character(20),
    mottaker_id character(20),
    opprettet_av character(7),
    opprettet_timestamp timestamp,
    enhetsnummer integer,
    CONSTRAINT stonad_pkey PRIMARY KEY (stonad_id),
    CONSTRAINT fk_vedtak_id FOREIGN KEY (vedtak_id)
        REFERENCES vedtak (vedtak_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    UNIQUE (stonad_type, skyldner_id, kravhaver_id)
)

    TABLESPACE pg_default;