-- Table: grunnlag

-- DROP TABLE grunnlag;

CREATE TABLE IF NOT EXISTS grunnlag
(
    grunnlagsid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    vedtaksid integer NOT NULL,
    referanse varchar(100) NOT NULL,
    type varchar(50) NOT NULL,
    innhold jsonb NOT NULL,
    CONSTRAINT grunnlag_pkey PRIMARY KEY (grunnlagsid),
    CONSTRAINT fk_vedtak_id FOREIGN KEY (vedtaksid)
        REFERENCES vedtak (vedtaksid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    UNIQUE (vedtaksid, referanse)
)

    TABLESPACE pg_default;

CREATE INDEX idx_grunnlag_1 ON grunnlag(vedtaksid);