-- Table: behandlingsreferanse

-- DROP TABLE behandlingsreferanse;

CREATE TABLE IF NOT EXISTS behandlingsreferanse
(
    behandlingsreferanse_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    vedtak_id integer NOT NULL,
    kilde text NOT NULL,
    referanse text NOT NULL,
    CONSTRAINT behandlingsreferanse_pkey PRIMARY KEY (behandlingsreferanse_id),
    CONSTRAINT fk_behandlingsreferanse_id FOREIGN KEY (vedtak_id)
        REFERENCES vedtak (vedtak_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    UNIQUE (vedtak_id, kilde, referanse)
)

    TABLESPACE pg_default;

CREATE INDEX idx_behandlingsreferanse_1 ON behandlingsreferanse(vedtak_id);