-- Table: periode

-- DROP TABLE grunnlag;

CREATE TABLE IF NOT EXISTS grunnlag
(
    grunnlag_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    grunnlag_referanse varchar(50),
    grunnlag_type varchar(20),
    grunnlag_innhold jsonb,
    opprettet_av character(7),
    opprettet_timestamp timestamp DEFAULT now(),
    CONSTRAINT grunnlag_pkey PRIMARY KEY (grunnlag_id)
)

    TABLESPACE pg_default;