-- Table: stønadsendring

-- DROP TABLE stønadsendring;

CREATE TABLE IF NOT EXISTS stønadsendring
(
    stønadsendringsid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    vedtaksid integer NOT NULL,
    type varchar(20) NOT NULL,
    sak varchar(20) NOT NULL,
    skyldner varchar(20) NOT NULL,
    kravhaver varchar(20) NOT NULL,
    mottaker varchar(20) NOT NULL,
    første_indeksreguleringsår integer,
    innkreving varchar(50) NOT NULL,
    beslutning varchar(50) NOT NULL,
    omgjør_vedtak_id integer,
    ekstern_referanse varchar(20),
    CONSTRAINT stønad_pkey PRIMARY KEY (stønadsendringsid),
    CONSTRAINT fk_vedtak_id FOREIGN KEY (vedtaksid)
        REFERENCES vedtak (vedtaksid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    UNIQUE (vedtaksid, type, skyldner, kravhaver, sak)
)
    TABLESPACE pg_default;

CREATE INDEX idx_stønadsendring_1 ON stønadsendring(vedtaksid) ;