-- Table: stonadsendring

-- DROP TABLE stonadsendring;

CREATE TABLE IF NOT EXISTS stonadsendring
(
    stonadsendring_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    stonad_type varchar(20),
    vedtak_id integer,
    behandling_id text,
    skyldner_id varchar(20),
    kravhaver_id varchar(20),
    mottaker_id varchar(20),
    opprettet_av character(7),
    opprettet_timestamp timestamp DEFAULT now(),
    CONSTRAINT stonad_pkey PRIMARY KEY (stonadsendring_id),
    CONSTRAINT fk_vedtak_id FOREIGN KEY (vedtak_id)
        REFERENCES vedtak (vedtak_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    UNIQUE (vedtak_id, stonad_type, skyldner_id, kravhaver_id)
)

    TABLESPACE pg_default;