name: Deploy to dev
on:
  push:
    branches:
      - 'test'

env:
  GITHUB_USERNAME: x-access-token
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    permissions:
      contents: "read"
      id-token: "write"
    name: Build with maven and docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn -DskipTests=true -B -e --settings .m2/maven-settings.xml clean install
      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: bidrag
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
    outputs:
      image: ${{ steps.docker-push.outputs.image }}
      version: ${{ steps.docker-push.outputs.new_version }}

  run-tests:
    runs-on: ubuntu-latest
    name: Run tests
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          path: deploy
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn -B -e --settings .m2/maven-settings.xml clean install

  deploy-main:
    runs-on: ubuntu-latest
    name: Deploy main
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          path: deploy
      - name: Deploy main branch to dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/.nais/nais.yaml
          VARS: deploy/.nais/main.yaml
          IMAGE: ${{ needs.build.outputs.image }}

  deploy-syntetisk:
    runs-on: ubuntu-latest
    name: Deploy syntetisk
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          path: deploy
      - name: Deploy to dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/.nais/nais.yaml
          VARS: deploy/.nais/syntetisk.yaml
          IMAGE: ${{ needs.build.outputs.image }}

  deploy-feature:
    runs-on: ubuntu-latest
    name: Deploy feature
    if: github.ref == 'refs/heads/main' || github.event_name != 'pull_request' || github.event.pull_request.draft == true
    needs: build

    steps:
      - uses: actions/checkout@v3
        with:
          path: deploy
      - name: Deploy to dev-gcp for feature.yaml
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/.nais/nais.yaml
          VARS: deploy/.nais/feature.yaml
          IMAGE: ${{ needs.build.outputs.image }}

  tag:
    runs-on: ubuntu-latest
    needs: deploy-syntetisk
    steps:
      - uses: actions/checkout@v3
      - name: Push latest image as tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.deploy-syntetisk.outputs.version }}
          name: Release test ${{ needs.deploy-syntetisk.outputs.version }}
          body: ${{ steps.tag_version.outputs.changelog }}

  run_cucumber_tests-main:
    runs-on: ubuntu-latest
    name: Run cucumber tests main
    needs: deploy-main

    env:
      INGRESS_CUCUMBER: https://bidrag-cucumber-cloud.ekstern.dev.nav.no
      INGRESS_VEDTAK: https://bidrag-vedtak.intern.dev.nav.no

    steps:
      - run: |
          curl -H "Content-Type: application/json" -i \
                -H "Authorization: Basic ${{ secrets.BIDRAG_CUCUMBER_CLOUD_AUTH }}" \
               --request POST \
               --data '{"noContextPathForApps":["bidrag-vedtak"],"ingressesForApps":[
                   "${{ env.INGRESS_VEDTAK }}@tag:bidrag-vedtak"
                 ]}' \
               ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-cloud/run | tee .cucumber-result
          cat .cucumber-result | grep HTTP/2 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)


  run_cucumber_tests-feature:
    runs-on: ubuntu-latest
    name: Run cucumber tests feature
    needs: deploy-feature

    env:
      INGRESS_CUCUMBER: https://bidrag-cucumber-cloud-feature.ekstern.dev.nav.no
      INGRESS_VEDTAK: https://bidrag-vedtak-feature.intern.dev.nav.no

    steps:
      - run: |
          curl -H "Content-Type: application/json" -i \
                -H "Authorization: Basic ${{ secrets.BIDRAG_CUCUMBER_CLOUD_AUTH }}" \
               --request POST \
               --data '{"noContextPathForApps":["bidrag-vedtak"],"ingressesForApps":[
                   "${{ env.INGRESS_VEDTAK }}@tag:bidrag-vedtak"
                 ]}' \
               ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-cloud/run | tee .cucumber-result
          cat .cucumber-result | grep HTTP/2 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
