name: Deploy q4
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
      - '!main'
      - '!q1/**'
      - '!Q1/**'
      - '!q2/**'
      - '!Q2/**'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-deploy:
    name: "Build and deploy to q4"
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy.yaml@main
    secrets: inherit
    with:
      nais_variabler_filnavn: q4.yaml